FROM python:3.11-slim

WORKDIR /inference-phase4


COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt
RUN pip install --no-cache-dir grpcio-tools

COPY . .
RUN python -m grpc_tools.protoc -I . --python_out=. --grpc_python_out=. inference.proto



# the gRPC port for inference
EXPOSE 50051
ENTRYPOINT ["python"]
CMD ["inference.py"]